version: '3'

services: 
   rabbitmq:
     image: rabbitmq:management
     ports: 
      - 15673:15672
      - 5673:5672
     environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
     
    